#include "compiler.h"
#include "lexer.h"
#include "parser.h"
#include "logger.h"
#include <iostream>
#include <fstream>
#include <sstream>

Compiler::Compiler() 
    : lexer(std::make_unique<Lexer>()),
      parser(std::make_unique<Parser>()) {}

Compiler::~Compiler() {}

bool Compiler::compile(const std::string& inputFile, const std::string& outputFile) {
    Logger& logger = Logger::getInstance();
    
    try {
        logger.info("Step 1: Reading source file...");
        std::string sourceCode;
        if (!readSourceFile(inputFile, sourceCode)) {
            logger.error("Failed to read input file: " + inputFile);
            std::cerr << "ERROR: Failed to read input file: " << inputFile << std::endl;
            return false;
        }
        logger.infof("OK: Read %zu bytes", sourceCode.length());

        logger.info("Step 2: Lexical analysis (tokenization)...");
        if (!lexer) {
            logger.error("Lexer not initialized");
            std::cerr << "ERROR: Lexer not initialized\n";
            return false;
        }
        
        auto tokens = lexer->tokenize(sourceCode);
        logger.infof("OK: Generated %zu tokens", tokens.size());

        logger.info("Step 3: Syntax analysis (parsing)...");
        if (!parser) {
            logger.error("Parser not initialized");
            std::cerr << "ERROR: Parser not initialized\n";
            return false;
        }
        
        auto ast = parser->parse(tokens);
        if (!ast) {
            logger.error("AST generation failed");
            std::cerr << "ERROR: AST generation failed\n";
            return false;
        }
        logger.info("OK: AST generated successfully");

        logger.info("Step 4: Code generation...");
        std::string generatedCode = "#include <iostream>\n";
        generatedCode += "#include <cstdint>\n\n";
        generatedCode += "/* Generated by W3D Compiler */\n\n";
        generatedCode += sourceCode;
        generatedCode += "\n\n/* Compilation complete */\n";
        logger.infof("OK: Code generated (%zu bytes)", generatedCode.length());

        logger.info("Step 5: Writing output file...");
        if (!writeOutputFile(outputFile, generatedCode)) {
            logger.error("Failed to write output file: " + outputFile);
            std::cerr << "ERROR: Failed to write output file: " << outputFile << std::endl;
            return false;
        }
        logger.info("OK: Output written to " + outputFile);

        logger.info("========================================");
        logger.info("SUCCESS: Compilation completed!");
        logger.info("========================================");
        return true;

    } catch (const std::exception& e) {
        logger.error("EXCEPTION: " + std::string(e.what()));
        std::cerr << "EXCEPTION: " << e.what() << std::endl;
        return false;
    } catch (...) {
        logger.critical("UNKNOWN ERROR: Unexpected exception occurred");
        std::cerr << "UNKNOWN ERROR: Unexpected exception occurred\n";
        return false;
    }
}

bool Compiler::readSourceFile(const std::string& filename, std::string& content) {
    Logger& logger = Logger::getInstance();
    
    try {
        std::ifstream file(filename, std::ios::in | std::ios::binary);
        
        if (!file.is_open()) {
            logger.warning("Cannot open file: " + filename);
            std::cerr << "  Cannot open file: " << filename << std::endl;
            return false;
        }

        file.seekg(0, std::ios::end);
        std::streamsize size = file.tellg();
        file.seekg(0, std::ios::beg);

        if (size > 10485760) {  // 10MB limit
            logger.error("File too large: " + std::to_string(size) + " bytes (max 10MB)");
            std::cerr << "  File too large: " << size << " bytes (max 10MB)\n";
            return false;
        }

        content.resize(size);
        if (!file.read(content.data(), size)) {
            logger.error("Error reading file data");
            std::cerr << "  Error reading file data\n";
            return false;
        }

        file.close();
        logger.infof("File size: %zu bytes", size);
        return true;

    } catch (const std::exception& e) {
        logger.error("Exception: " + std::string(e.what()));
        std::cerr << "  Exception: " << e.what() << std::endl;
        return false;
    }
}

bool Compiler::writeOutputFile(const std::string& filename, const std::string& content) {
    Logger& logger = Logger::getInstance();
    
    try {
        std::ofstream file(filename, std::ios::out | std::ios::binary);
        
        if (!file.is_open()) {
            logger.warning("Cannot create file: " + filename);
            std::cerr << "  Cannot create file: " << filename << std::endl;
            return false;
        }

        if (!file.write(content.c_str(), content.length())) {
            logger.error("Error writing file data");
            std::cerr << "  Error writing file data\n";
            return false;
        }

        file.close();
        logger.infof("File size: %zu bytes", content.length());
        return true;

    } catch (const std::exception& e) {
        logger.error("Exception: " + std::string(e.what()));
        std::cerr << "  Exception: " << e.what() << std::endl;
        return false;
    }
}
