#include "compiler.h"
#include "lexer.h"
#include "parser.h"
#include "logger.h"
#include "ui.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <chrono>

Compiler::Compiler() 
    : lexer(std::make_unique<Lexer>()),
      parser(std::make_unique<Parser>()) {}

Compiler::~Compiler() {}

bool Compiler::compile(const std::string& inputFile, const std::string& outputFile) {
    Logger& logger = Logger::getInstance();
    auto startTime = std::chrono::high_resolution_clock::now();
    
    try {
        // Шаг 1: Чтение файла
        UI::printStep(1, "Reading source file");
        std::string sourceCode;
        
        UI::printSubStep("Opening file: " + inputFile);
        if (!readSourceFile(inputFile, sourceCode)) {
            UI::printError("Failed to read input file: " + inputFile);
            logger.error("Failed to read input file: " + inputFile);
            return false;
        }
        
        UI::printSuccess("File read successfully");
        UI::printStats("File size", std::to_string(sourceCode.length()) + " bytes");
        logger.infof("OK: Read %zu bytes", sourceCode.length());

        // Шаг 2: Лексический анализ
        UI::printStep(2, "Lexical analysis (tokenization)");
        
        if (!lexer) {
            UI::printError("Lexer not initialized");
            logger.error("Lexer not initialized");
            return false;
        }
        
        UI::printSubStep("Tokenizing source code...");
        auto tokens = lexer->tokenize(sourceCode);
        
        UI::printSuccess("Tokenization completed");
        UI::printStats("Generated tokens", std::to_string(tokens.size()) + " tokens");
        logger.infof("OK: Generated %zu tokens", tokens.size());

        // Шаг 3: Синтаксический анализ
        UI::printStep(3, "Syntax analysis (parsing)");
        
        if (!parser) {
            UI::printError("Parser not initialized");
            logger.error("Parser not initialized");
            return false;
        }
        
        UI::printSubStep("Building Abstract Syntax Tree (AST)...");
        auto ast = parser->parse(tokens);
        
        if (!ast) {
            UI::printError("AST generation failed");
            logger.error("AST generation failed");
            return false;
        }
        
        UI::printSuccess("AST generated successfully");
        logger.info("OK: AST generated successfully");

        // Шаг 4: Генерация кода
        UI::printStep(4, "Code generation");
        
        UI::printSubStep("Generating C++ code with headers...");
        std::string generatedCode = "#include <iostream>\n";
        generatedCode += "#include <cstdint>\n";
        generatedCode += "#include <vector>\n\n";
        generatedCode += "/* Generated by W3D Compiler - Wolfenstein 3D C to C++ */\n";
        generatedCode += "/* Input: " + inputFile + " */\n\n";
        generatedCode += sourceCode;
        generatedCode += "\n\n/* Compilation complete */\n";
        
        UI::printSuccess("Code generated");
        UI::printStats("Generated code size", std::to_string(generatedCode.length()) + " bytes");
        logger.infof("OK: Code generated (%zu bytes)", generatedCode.length());

        // Шаг 5: Запись файла
        UI::printStep(5, "Writing output file");
        
        UI::printSubStep("Creating output file: " + outputFile);
        if (!writeOutputFile(outputFile, generatedCode)) {
            UI::printError("Failed to write output file: " + outputFile);
            logger.error("Failed to write output file: " + outputFile);
            return false;
        }
        
        UI::printSuccess("Output file written successfully");
        UI::printStats("Output file", outputFile);
        logger.info("OK: Output written to " + outputFile);

        // Финальная статистика
        auto endTime = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime);
        
        std::cout << "\n";
        UI::printSeparator('=', 70);
        UI::printColored(UI::centerText("✓ COMPILATION SUCCESSFUL", 70), UI::Color::GREEN);
        UI::printSeparator('=', 70);
        
        std::cout << "\n";
        UI::printStatsHeader();
        UI::printStats("Input file", inputFile);
        UI::printStats("Output file", outputFile);
        UI::printStats("Source code size", std::to_string(sourceCode.length()) + " bytes");
        UI::printStats("Tokens generated", std::to_string(tokens.size()));
        UI::printStats("Output code size", std::to_string(generatedCode.length()) + " bytes");
        UI::printStats("Compilation time", std::to_string(duration.count()) + " ms");
        UI::printStatsFooter();
        
        logger.info("========================================");
        logger.info("SUCCESS: Compilation completed in " + std::to_string(duration.count()) + "ms");
        logger.info("========================================");
        
        return true;

    } catch (const std::exception& e) {
        std::cout << "\n";
        UI::printError("Exception occurred: " + std::string(e.what()));
        logger.error("EXCEPTION: " + std::string(e.what()));
        return false;
    } catch (...) {
        std::cout << "\n";
        UI::printError("Unknown error: Unexpected exception occurred");
        logger.critical("UNKNOWN ERROR: Unexpected exception occurred");
        return false;
    }
}

bool Compiler::readSourceFile(const std::string& filename, std::string& content) {
    Logger& logger = Logger::getInstance();
    
    try {
        std::ifstream file(filename, std::ios::in | std::ios::binary);
        
        if (!file.is_open()) {
            logger.warning("Cannot open file: " + filename);
            return false;
        }

        file.seekg(0, std::ios::end);
        std::streamsize size = file.tellg();
        file.seekg(0, std::ios::beg);

        if (size > 10485760) {  // 10MB limit
            UI::printWarning("File too large: " + std::to_string(size) + " bytes (max 10MB)");
            logger.error("File too large: " + std::to_string(size) + " bytes (max 10MB)");
            return false;
        }

        content.resize(size);
        if (!file.read(content.data(), size)) {
            logger.error("Error reading file data");
            return false;
        }

        file.close();
        logger.infof("File size: %zu bytes", size);
        return true;

    } catch (const std::exception& e) {
        logger.error("Exception: " + std::string(e.what()));
        return false;
    }
}

bool Compiler::writeOutputFile(const std::string& filename, const std::string& content) {
    Logger& logger = Logger::getInstance();
    
    try {
        std::ofstream file(filename, std::ios::out | std::ios::binary);
        
        if (!file.is_open()) {
            logger.warning("Cannot create file: " + filename);
            return false;
        }

        if (!file.write(content.c_str(), content.length())) {
            logger.error("Error writing file data");
            return false;
        }

        file.close();
        logger.infof("Output file size: %zu bytes", content.length());
        return true;

    } catch (const std::exception& e) {
        logger.error("Exception: " + std::string(e.what()));
        return false;
    }
}
